# Generated by Django 5.0.1 on 2025-05-10 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_militar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(help_text='Dirección (puede contener letras, números, espacios y los caracteres - N *)', max_length=60, validators=[django.core.validators.RegexValidator(message='La dirección solo puede contener letras, números, espacios y los caracteres - N *', regex='^[a-zA-Z0-9\\s\\-N*]+$')]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cel_phone',
            field=models.CharField(help_text='Número de celular (solo dígitos)', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener solo dígitos', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='emergency_phone',
            field=models.CharField(help_text='Número de teléfono de emergencia (solo dígitos)', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener solo dígitos', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(help_text='Número de teléfono (solo dígitos)', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener solo dígitos', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document',
            field=models.CharField(blank=True, help_text='Número de documento', max_length=20),
        ),
    ]
